export const CLICKED_BUTTON_SUCCESS = 'CLICKED_BUTTON_SUCCESS';
export const CLICKED_BUTTON_REQUEST = 'CLICKED_BUTTON_REQUEST';
export const CLICKED_BUTTON_FAILURE = 'CLICKED_BUTTON_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const REGISTER_CREATED_SUCCESS = 'REGISTER_CREATED_SUCCESS';
export const REGISTER_UPDATED_SUCCESS = 'REGISTER_UPDATED_SUCCESS';

export const PASSWORD_RESTORE_REQUEST = 'PASSWORD_RESTORE_REQUEST';
export const PASSWORD_RESTORE_SUCCESS = 'PASSWORD_RESTORE_SUCCESS';
export const PASSWORD_RESTORE_FAILURE = 'PASSWORD_RESTORE_FAILURE';

export const PASSWORD_RESET_REQUEST = 'PASSWORD_RESET_REQUEST';
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
export const PASSWORD_RESET_FAILURE = 'PASSWORD_RESET_FAILURE';

export const PERSIST_REHYDRATE = 'persist/REHYDRATE';
